# Generated by Django 5.2.7 on 2026-04-23 19:59

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_name', models.CharField(max_length=124, unique=True)),
            ],
            options={
                'db_table': 'Olympiad',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30, unique=True)),
                ('icon', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Xp_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('xp_required', models.PositiveIntegerField()),
                ('icon', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'Xp_level',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(max_length=48, unique=True)),
                ('olympiad', models.ManyToManyField(to='myapp.olympiad')),
            ],
            options={
                'db_table': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=33)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='myapp.subject')),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.AddField(
            model_name='olympiad',
            name='topic',
            field=models.ManyToManyField(to='myapp.topic'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type_number', models.IntegerField()),
                ('type', models.CharField(max_length=15)),
                ('source', models.TextField(null=True)),
                ('xp', models.IntegerField(default=10)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('topic', models.ManyToManyField(to='myapp.topic')),
            ],
            options={
                'db_table': 'Card',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=117, unique=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('direction', models.ManyToManyField(to='myapp.direction')),
            ],
            options={
                'db_table': 'University',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('icon', models.ImageField(default='images/default_avatar.png', upload_to='images/')),
                ('xp', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(default=myapp.models.get_default_role, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapp.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_do', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.card')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_topic', to='myapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for', to='myapp.user')),
            ],
            options={
                'db_table': 'Task',
                'unique_together': {('user', 'card')},
            },
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_solved', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved', to='myapp.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_by', to='myapp.user')),
            ],
            options={
                'db_table': 'Solved',
                'unique_together': {('user', 'card')},
            },
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to='myapp.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='myapp.user')),
            ],
            options={
                'db_table': 'Read',
                'unique_together': {('user', 'card')},
            },
        ),
        migrations.CreateModel(
            name='Planned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(default='topic', max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_card', to='myapp.card')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_topic', to='myapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_by', to='myapp.user')),
            ],
            options={
                'db_table': 'Planned',
                'unique_together': {('user', 'topic', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='OlympiadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_date', models.DateTimeField(null=True)),
                ('olympiad_start_date', models.DateTimeField()),
                ('olympiad_end_date', models.DateTimeField()),
                ('notified_7d', models.BooleanField(default=False)),
                ('notified_1d', models.BooleanField(default=False)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.olympiad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_notifications', to='myapp.user')),
            ],
            options={
                'db_table': 'OlympiadNotification',
                'unique_together': {('user', 'olympiad')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='myapp.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_by', to='myapp.user')),
            ],
            options={
                'db_table': 'Favorites',
                'unique_together': {('user', 'card')},
            },
        ),
    ]
