# Generated by Django 5.2.7 on 2026-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_university_link_alter_university_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiadnotification',
            name='notified_1d',
        ),
        migrations.RemoveField(
            model_name='olympiadnotification',
            name='notified_7d',
        ),
        migrations.RemoveField(
            model_name='olympiadnotification',
            name='olympiad_date',
        ),
        migrations.RemoveField(
            model_name='olympiadnotification',
            name='olympiad_end_date',
        ),
        migrations.RemoveField(
            model_name='olympiadnotification',
            name='olympiad_start_date',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
