# Generated by Django 5.2.7 on 2026-05-10 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_olympiadnotification_notified_1d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planned',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_card', to='myapp.card'),
        ),
        migrations.AlterField(
            model_name='planned',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_topic', to='myapp.topic'),
        ),
    ]
