# Generated by Django 5.2.7 on 2026-05-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_planned_card_alter_planned_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.card'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_topic', to='myapp.topic'),
        ),
    ]
