# Generated by Django 5.2.7 on 2026-05-12 10:02

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_task_card_alter_task_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=myapp.models.get_default_role, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapp.role'),
        ),
    ]
